spring:
  datasource:
      user:
        jdbcUrl: jdbc:postgresql://localhost:5432/userdb
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
      product:
        jdbcUrl: jdbc:postgresql://localhost:5432/productdb
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
